export const SET_ICON_TEXT_SIZE = 'SET_ICON_TEXT_SIZE';
export const SET_12_HOUR_TIME = 'SET_12_HOUR_TIME';

export const SET_THEME_MODE = 'SET_THEME_MODE';

export const ADD_APPLET_TO_ACTIVE = 'ADD_APPLET_TO_ACTIVE';
export const REMOVE_APPLET_FROM_ACTIVE = 'REMOVE_APPLET_FROM_ACTIVE';
export const SET_APPLET_TOP = 'SET_APPLET_TOP';
export const SET_APPLET_SIZE = 'SET_APPLET_SIZE';
export const SET_APPLET_POSITION = 'SET_APPLET_POSITION';
