export const GET_WIDGET_STATUS = 'GET_WIDGET_STATUS';
export const SET_TEXT_WIDGET_ACTIVE = 'SET_TEXT_WIDGET_ACTIVE';
export const SET_SETTINGS_WIDGET_ACTIVE = 'SET_SETTINGS_WIDGET_ACTIVE';
export const SET_TEXT_WIDGET_INACTIVE = 'SET_TEXT_WIDGET_INACTIVE';
export const SET_SETTINGS_WIDGET_INACTIVE = 'SET_SETTINGS_WIDGET_INACTIVE';

export const GET_TEXT_WIDGET = 'GET_TEXT_WIDGET';
export const SET_TEXT_WIDGET_POS = 'SET_TEXT_WIDGET_POS';
export const SET_TEXT_WIDGET_SIZE = 'SET_TEXT_WIDGET_SIZE';

export const GET_SETTINGS_WIDGET = 'GET_SETTINGS_WIDGET';
export const SET_SETTINGS_WIDGET_POS = 'SET_SETTINGS_WIDGET_POS';
export const SET_SETTINGS_WIDGET_SIZE = 'SET_SETTINGS_WIDGET_SIZE';

export const GET_CLI_WIDGET = 'GET_CLI_WIDGET';
export const SET_CLI_WIDGET_POS = 'SET_CLI_WIDGET_POS';
export const SET_CLI_WIDGET_SIZE = 'SET_CLI_WIDGET_SIZE';
